title: Welcome to my portfolio!
author: CyberVA
theme: jekyll-theme-cayman
description: >
  Here's a cool description for this website that is an assignment for 342!!!

github_username: CyberVA

show_excerpts: true
